# Generated by Django 4.0.4 on 2022-10-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_attendance__1_alter_attendance__10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
