# Generated by Django 4.0.4 on 2022-10-07 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_contanct_student_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='facereader/known'),
            preserve_default=False,
        ),
    ]
