# Generated by Django 4.0.4 on 2022-10-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(upload_to='face_attendance/static/known'),
        ),
    ]
