from django.db import models
from account.models import student, teacher
# Create your models here.

class attendance(models.Model):
    student = models.ForeignKey(student, on_delete=models.CASCADE)
    teacher = models.ForeignKey(teacher, on_delete=models.CASCADE, null=True)
    month = models.SmallIntegerField(default=-1)
    year = models.SmallIntegerField(default=-1)
    d_1 = models.SmallIntegerField(default=-1)
    d_2 = models.SmallIntegerField(default=-1)
    d_3 = models.SmallIntegerField(default=-1)
    d_4 = models.SmallIntegerField(default=-1)
    d_5 = models.SmallIntegerField(default=-1)
    d_6 = models.SmallIntegerField(default=-1)
    d_7 = models.SmallIntegerField(default=-1)
    d_8 = models.SmallIntegerField(default=-1)
    d_9 = models.SmallIntegerField(default=-1)
    d_10 = models.SmallIntegerField(default=-1)
    d_11 = models.SmallIntegerField(default=-1)
    d_12 = models.SmallIntegerField(default=-1)
    d_13 = models.SmallIntegerField(default=-1)
    d_14 = models.SmallIntegerField(default=-1)
    d_15 = models.SmallIntegerField(default=-1)
    d_16 = models.SmallIntegerField(default=-1)
    d_17 = models.SmallIntegerField(default=-1)
    d_18 = models.SmallIntegerField(default=-1)
    d_19 = models.SmallIntegerField(default=-1)
    d_20 = models.SmallIntegerField(default=-1)
    d_21 = models.SmallIntegerField(default=-1)
    d_22 = models.SmallIntegerField(default=-1)
    d_23 = models.SmallIntegerField(default=-1)
    d_24 = models.SmallIntegerField(default=-1)
    d_25 = models.SmallIntegerField(default=-1)
    d_26 = models.SmallIntegerField(default=-1)
    d_27 = models.SmallIntegerField(default=-1)
    d_28 = models.SmallIntegerField(default=-1)
    d_29 = models.SmallIntegerField(default=-1)
    d_30 = models.SmallIntegerField(default=-1)
    d_31 = models.SmallIntegerField(default=-1)