# Generated by Django 4.0.4 on 2022-10-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
